### ISSUE TITLE
Building with Rossum : Operator not defined on REALS

### ISSUE THREAD

**Issue by kevinAlfsen** [kobbled/kl-math#2]
I get this error when trying to build with rossum:

FAILED: C:/Users/me/Ka-Boost/lib/math/build/math.pc
"C:\Users\me\Rossum\deps\ktransw\bin\ktransw.cmd" -q  -MM -MP -MT "C:\Users\me\Ka-Boost\lib\math\build\math.pc" 
-MF "C:\Users\me\Ka-Boost\lib\math\build\math.pc".d 
--ktrans="C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" 
/I"C:\Users\me\Ka-Boost\lib\math\include" 
/I"C:\Users\me\Ka-Boost\lib\math\include\classes" 
/I"C:\Users\me\Ka-Boost\lib\math\test\test_types" 
/I"C:\Users\me\Ka-Boost\lib\Strings\include" 
/I"C:\Users\me\Ka-Boost\lib\errors\include" 
/I"C:\Users\me\Ka-Boost\lib\system\include" 
/I"C:\Users\me\Ka-Boost\lib\ktransw-macros\include" 
/I"C:\Users\me\Documents\My Workcells\WeldPRO3\Robot_1\support"  "C:\Users\me\Ka-Boost\lib\math\src\math.kl" 
/ver V9.40-1 /config "C:\Users\me\Ka-Boost\lib\math\build\robot.ini"

KTRANS Version V9.40 (Build 83   4/22/2021)
Copyright (C) FANUC America Corporation, 1985 through 2019.
All Rights Reserved.

C:\Users\me\Ka-Boost\lib\math\src\math.kl(204)
 204     IF ABS(ajacent) < 0.0001 AND ABS(opposite) < 0.0001 THEN
                                    ^ ERROR
Operator not defined on REALS.

C:\Users\me\Ka-Boost\lib\math\src\math.kl(211)
 211     IF ABS(pose.x) < 0.0001 AND ABS(pose.y) < 0.0001 THEN
                                   ^ ERROR
Operator not defined on REALS.

I am not very experienced with Karel yet, so I don't know if this is correct, but should this have been preprocessed with parantheses? Like this: 

IF (ABS(ajacent) < 0.0001) AND (ABS(opposite) < 0.0001) THEN
    ...

I figured a quick and dirty workaround would be for me to just fix these lines in the source, but since they are added through preprocessor directives, I cannot seem to find the source for these lines. 

If this is not a quick fix, could you point me to a workaround, so that I can start using the library?

**Comment by kevinAlfsen** [comment]
[math.kl.txt](https://github.com/kobbled/kl-math/files/10767022/math.kl.txt)

Here is the preprocessed math.kl, compiled with "rossum .. -s -E".

The error points to line 204 and 211 which are the math_atan and math_atanp functions.

**Comment by kevinAlfsen** [comment]
It seems [265fc3e](https://github.com/kobbled/kl-math/commit/265fc3e91ff6c019e32f990a46cdb7dd7edc992a) fixed my issue

**Comment by kobbled** [comment]
Hi @kevinAlfsen, thank you for flagging the issue. I must have pushed the update without running it through kunit first. The module builds and passes all the unit tests for me. If you're still having troubles please post another issue. Even knowing that other people are using this is helpful! Since there isn't any documentation for this I have opened up a discussions section in  https://github.com/kobbled/Ka-Boost/discussions, if you are struggling with anything, or need me to walk you through something, please post there. Thanks!
